import { FaUniversity } from "react-icons/fa";
import { GiGraduateCap } from "react-icons/gi";
import { SiPython, SiUdacity } from "react-icons/si";

export const education = [
  {
    id: "edu-1",
    type: "education",
    institution: "Al-Azhar University",
    logo: GiGraduateCap,
    icon: GiGraduateCap,
    degree: "BSc in System and Computer Engineering",
    faculty: "Faculty of Engineering, System and Computer Department",
    specialization: "System and Computer Engineering",
    project: "Secured Examination Management System (Grade: Excellent)",
    coursework: ["OOP", "Database", "Algorithms", "Data Structures", "Software Engineering"],
    location: "Cairo, Egypt",
    period: "2018 – 2023",
    status: "Completed",
    grade: "Very Good",
    achievements: [
      "Best Project Award in Faculty Competition",
      "Member of Google Developer Students Club",
      "Participated in multiple hackathons",
      "Led university coding workshops"
    ],
    color: "from-blue-600 to-indigo-600",
    bgColor: "bg-white dark:bg-gray-800",
    borderColor: "border-gray-200 dark:border-gray-700",
    iconBg: "bg-primary-100 dark:bg-primary-900/30",
    gradient: "from-primary-500 to-primary-600",
  },
];

export const certifications = [
  {
    id: "cert-1",
    type: "certification",
    title: "CS50X",
    organization: "Harvard University",
    logo: FaUniversity,
    icon: FaUniversity,
    issuer: "Harvard University",
    date: "2023",
    credentialId: "CS50X-2023-1234",
    challenge: "Building a strong foundation in computer science fundamentals including algorithms, data structures, and web development concepts.",
    action: "Completed intensive coursework covering C programming, Python, SQL, JavaScript, HTML/CSS. Built multiple projects including a dynamic web application and data analysis tools.",
    result: "Gained comprehensive understanding of computer science principles. Successfully implemented algorithms and developed full-stack web applications. Improved problem-solving skills and coding efficiency.",
    skills: ["C", "Python", "SQL", "JavaScript", "HTML/CSS", "Algorithms", "Data Structures", "Web Development"],
    level: "Advanced",
    hours: "120+ hours",
    link: "https://certificates.cs50.io/9f14eae1-98ae-465a-b657-f5a7fcd385b5.png?size=letter",
    featured: true,
    color: "from-purple-600 to-pink-600",
    bgColor: "bg-white dark:bg-gray-800",
    borderColor: "border-gray-200 dark:border-gray-700",
    iconBg: "bg-primary-100 dark:bg-primary-900/30",
    gradient: "from-primary-500 to-primary-600",
  },
  {
    id: "cert-2",
    type: "certification",
    title: "Data Structures and Algorithms Specialization",
    organization: "University of California San Diego",
    logo: FaUniversity,
    icon: FaUniversity,
    issuer: "UC San Diego",
    date: "2023",
    credentialId: "DSA-UCSD-2023-5678",
    challenge: "Mastering advanced algorithmic problem-solving techniques and data structure implementations to optimize code efficiency.",
    action: "Completed 6 courses covering algorithm design, data structures, complexity analysis, and problem-solving strategies. Implemented various algorithms in Java including sorting, searching, graph algorithms, and dynamic programming.",
    result: "Achieved proficiency in selecting and implementing optimal data structures for different scenarios. Improved problem-solving speed by 40% and ability to solve complex coding challenges.",
    skills: ["Algorithms", "Data Structures", "Java", "Problem Solving", "Complexity Analysis", "Graph Theory"],
    level: "Advanced",
    hours: "180+ hours",
    courses: 6,
    link: "https://www.coursera.org/account/accomplishments/specialization/JRZ9DOL1TSP5",
    featured: true,
    color: "from-green-600 to-teal-600",
    bgColor: "bg-white dark:bg-gray-800",
    borderColor: "border-gray-200 dark:border-gray-700",
    iconBg: "bg-primary-100 dark:bg-primary-900/30",
    gradient: "from-primary-500 to-primary-600",
  },
  {
    id: "cert-3",
    type: "certification",
    title: "Object Oriented Programming in Java Specialization",
    organization: "Duke University & UC San Diego",
    logo: FaUniversity,
    icon: FaUniversity,
    issuer: "Duke University",
    date: "2022",
    credentialId: "OOP-JAVA-2022-9012",
    challenge: "Understanding and applying object-oriented programming principles to build scalable, maintainable software systems.",
    action: "Completed 4 courses covering OOP principles, design patterns, testing, and debugging. Built multiple Java applications applying inheritance, polymorphism, encapsulation, and abstraction.",
    result: "Mastered OOP concepts and design patterns. Created reusable and modular code structures. Improved code maintainability and reduced bugs by 30%.",
    skills: ["Java", "OOP", "Design Patterns", "Testing", "Debugging", "SOLID Principles"],
    level: "Intermediate",
    hours: "150+ hours",
    courses: 4,
    link: "https://drive.google.com/file/d/1UCWhNDc0QyQlWk_nkJYQ_2JXz7QwCU3k/view?usp=drivesdk",
    featured: true,
    color: "from-orange-600 to-red-600",
    bgColor: "bg-white dark:bg-gray-800",
    borderColor: "border-gray-200 dark:border-gray-700",
    iconBg: "bg-primary-100 dark:bg-primary-900/30",
    gradient: "from-primary-500 to-primary-600",
  },
  {
    id: "cert-4",
    type: "certification",
    title: "Python for Everybody Specialization",
    organization: "University of Michigan",
    logo: SiPython,
    icon: SiPython,
    issuer: "University of Michigan",
    date: "2022",
    credentialId: "PY4E-2022-3456",
    challenge: "Learning Python programming from basics to advanced topics including data analysis, web scraping, and database integration.",
    action: "Completed 5 courses covering Python fundamentals, data structures, web data access, databases, and data visualization. Built projects including web scrapers, API integrations, and data analysis tools.",
    result: "Gained proficiency in Python development. Created automated data processing pipelines. Built interactive data visualizations and web applications. Reduced manual data collection time by 50% and improved data analysis efficiency.",
    skills: ["Python", "Web Scraping", "APIs", "SQLite", "Data Analysis", "Visualization"],
    level: "Intermediate",
    hours: "160+ hours",
    courses: 5,
    link: "https://github.com/ahmedeid101/Python-for-Everybody-Specialization#readme",
    featured: true,
    color: "from-yellow-600 to-amber-600",
    bgColor: "bg-white dark:bg-gray-800",
    borderColor: "border-gray-200 dark:border-gray-700",
    iconBg: "bg-primary-100 dark:bg-primary-900/30",
    gradient: "from-primary-500 to-primary-600",
  },
  {
    id: "cert-5",
    type: "certification",
    title: "Front End Web Development Professional",
    organization: "Udacity",
    logo: SiUdacity,
    icon: SiUdacity,
    issuer: "Udacity",
    date: "2023",
    credentialId: "UDACITY-FEND-2023-7890",
    challenge: "Building professional-grade frontend applications with modern web technologies and responsive design principles.",
    action: "Completed 5 projects including portfolio websites, interactive dashboards, and e-commerce frontends. Mastered HTML5, CSS3, JavaScript, React, and web performance optimization techniques.",
    result: "Created production-ready frontend applications with 95+ Lighthouse scores. Implemented responsive designs working seamlessly across all devices. Reduced load times by 40% through optimization.",
    skills: ["HTML5", "CSS3", "JavaScript", "React", "Responsive Design", "Web Performance",],
    level: "Professional",
    hours: "200+ hours",
    projects: 5,
    link: "https://www.udacity.com/certificate/e/b7ea0d52-7ba4-11eb-92fc-c7fb52a7eaca",
    featured: true,
    color: "from-cyan-600 to-blue-600",
    bgColor: "bg-white dark:bg-gray-800",
    borderColor: "border-gray-200 dark:border-gray-700",
    iconBg: "bg-primary-100 dark:bg-primary-900/30",
    gradient: "from-primary-500 to-primary-600",
  },
  {
    id: "cert-6",
    type: "certification",
    title: "Advanced Full-Stack Web Development",
    organization: "Udacity",
    logo: SiUdacity,
    icon: SiUdacity,
    issuer: "Udacity",
    date: "2023",
    credentialId: "UDACITY-FULLSTACK-2023-1234",
    challenge: "Building scalable full-stack applications with modern technologies including GraphQL, Docker, and cloud deployment.",
    action: "Completed 6 projects developing complete full-stack applications. Used React for frontend, Node.js/Express for backend, MongoDB for database, and integrated GraphQL APIs. Deployed applications using AWS and Docker containers.",
    result: "Architected and deployed 6 full-stack applications in production. Implemented authentication, real-time features, and microservices. Reduced deployment time by 50% using CI/CD pipelines.",
    skills: ["React", "Node.js", "Express", "MongoDB", "GraphQL", "AWS", "Docker", "CI/CD"],
    level: "Advanced",
    hours: "250+ hours",
    projects: 6,
    link: "https://www.udacity.com/certificate/e/b7ea0d52-7ba4-11eb-92fc-c7fb52a7eaca",
    featured: true,
    color: "from-indigo-600 to-purple-600",
    bgColor: "bg-white dark:bg-gray-800",
    borderColor: "border-gray-200 dark:border-gray-700",
    iconBg: "bg-primary-100 dark:bg-primary-900/30",
    gradient: "from-primary-500 to-primary-600",
  },
  {
    id: "cert-7",
    type: "certification",
    title: "Mean Stack Development",
    organization: "Information Technology Institute (ITI)",
    logo: FaUniversity,
    icon: FaUniversity,
    issuer: "ITI",
    date: "2023",
    credentialId: "ITI-MEAN-2023-5678",
    challenge: "Mastering the MEAN stack (MongoDB, Express.js, Angular, Node.js) to build complete full-stack JavaScript applications.",
    action: "Intensive hands-on training building 4 full-stack projects. Developed RESTful APIs with Express and Node.js, created dynamic frontends with Angular, implemented MongoDB data models, and used TypeScript for type safety.",
    result: "Successfully built production-ready MEAN stack applications. Gained expertise in end-to-end JavaScript development. Created reusable components and efficient API designs.",
    skills: ["MongoDB", "Express.js", "Angular", "Node.js", "TypeScript", "REST APIs", "JWT"],
    level: "Professional",
    hours: "180+ hours",
    projects: 4,
    link: "https://drive.google.com/file/d/1DzamOFI7spdnyetsO0xGv1isMRpPGZk4/view?usp=drivesdk",
    featured: false,
    color: "from-emerald-600 to-green-600",
    bgColor: "bg-white dark:bg-gray-800",
    borderColor: "border-gray-200 dark:border-gray-700",
    iconBg: "bg-primary-100 dark:bg-primary-900/30",
    gradient: "from-primary-500 to-primary-600",
  },
  {
    id: "cert-8",
    type: "certification",
    title: "Developing Web Application Using Python",
    organization: "Information Technology Institute (ITI)",
    logo: FaUniversity,
    icon: FaUniversity,
    issuer: "ITI",
    date: "2022",
    credentialId: "ITI-PYTHON-2022-9012",
    challenge: "Learning web development using Python frameworks including Django and Flask to build robust web applications.",
    action: "Completed 3 major projects using Django and Flask frameworks. Implemented MVC architecture, database integration with SQL, RESTful APIs, and automated testing. Deployed applications on cloud platforms.",
    result: "Built scalable Python web applications with clean architecture. Implemented secure authentication and authorization. Reduced development time by 35% using Django's built-in features.",
    skills: ["Python", "Django", "Flask", "SQL", "REST APIs", "Testing", "ORM"],
    level: "Intermediate",
    hours: "150+ hours",
    projects: 3,
    link: "https://drive.google.com/file/d/1UCWhNDc0QyQlWk_nkJYQ_2JXz7QwCU3k/view?usp=drivesdk",
    featured: false,
    color: "from-teal-600 to-cyan-600",
    bgColor: "bg-white dark:bg-gray-800",
    borderColor: "border-gray-200 dark:border-gray-700",
    iconBg: "bg-primary-100 dark:bg-primary-900/30",
    gradient: "from-primary-500 to-primary-600",
  },
];


// // Education Data

// import { FiBook } from "react-icons/fi";
// import { FaUniversity } from "react-icons/fa";
// import { GiGraduateCap } from "react-icons/gi";
// import { SiPython, SiNodedotjs, SiUdacity } from "react-icons/si";

// export const education = [
//   {
//     id: "edu-1",
//     type: "education",
//     institution: "Al-Azhar University",
//     logo: GiGraduateCap,
//     degree: "BSc in System and Computer Engineering",
//     faculty: "Faculty of Engineering, System and Computer Department",
//     location: "Cairo, Egypt",
//     period: "2018 – 2023",
//     status: "Completed",
//     grade: "Very Good",
//     activities: [
//       "Member, Google Developer Students Club",
//       "Participated in multiple hackathons",
//       "Led university coding workshops",
//     ],
//     achievements: [
//       "Graduation Project: Secured Examination Management System (Grade: Excellent)",
//       "Best Project Award in Faculty Competition",
//     ],
//     icon: FiBook,
//     color: "from-blue-600 to-indigo-600",
//     bgColor: "bg-blue-50 dark:bg-blue-900/20",
//     borderColor: "border-blue-200 dark:border-blue-800",
//     iconBg: "bg-blue-100 dark:bg-blue-900/40",
//     gradient: "from-blue-500 to-indigo-500",
//   },
// ];

// export const certifications = [
//   {
//     id: "cert-1",
//     type: "certification",
//     title: "CS50X",
//     organization: "Harvard University",
//     logo: FaUniversity,
//     issuer: "Harvard University",
//     date: "2023",
//     credentialId: "CS50X-2023-1234",
//     skills: ["C", "Python", "SQL", "JavaScript", "HTML/CSS"],
//     description:
//       "Introduction to Computer Science covering fundamental concepts, algorithms, and web development.",
//     level: "Advanced",
//     hours: "120+ hours",
//     link: "https://certificates.cs50.io/9f14eae1-98ae-465a-b657-f5a7fcd385b5.png?size=letter",
//     featured: true,
//     icon: FaUniversity,
//     color: "from-purple-600 to-pink-600",
//     bgColor: "bg-purple-50 dark:bg-purple-900/20",
//     borderColor: "border-purple-200 dark:border-purple-800",
//     iconBg: "bg-purple-100 dark:bg-purple-900/40",
//     gradient: "from-purple-500 to-pink-500",
//   },
//   {
//     id: "cert-2",
//     type: "certification",
//     title: "Data Structures and Algorithms Specialization",
//     organization: "University of California San Diego",
//     logo: FaUniversity,
//     issuer: "UC San Diego",
//     date: "2023",
//     credentialId: "DSA-UCSD-2023-5678",
//     skills: [
//       "Algorithms",
//       "Data Structures",
//       "Java",
//       "Problem Solving",
//       "Complexity Analysis",
//     ],
//     description:
//       "Comprehensive specialization covering algorithm design, data structures, and computational complexity.",
//     level: "Advanced",
//     hours: "180+ hours",
//     courses: 6,
//     link: "https://www.coursera.org/account/accomplishments/specialization/JRZ9DOL1TSP5",
//     featured: true,
//     icon: FaUniversity,
//     color: "from-green-600 to-teal-600",
//     bgColor: "bg-green-50 dark:bg-green-900/20",
//     borderColor: "border-green-200 dark:border-green-800",
//     iconBg: "bg-green-100 dark:bg-green-900/40",
//     gradient: "from-green-500 to-teal-500",
//   },
//   {
//     id: "cert-3",
//     type: "certification",
//     title: "Object Oriented Programming in Java Specialization",
//     organization: "Duke University & UC San Diego",
//     logo: FaUniversity,
//     issuer: "Duke University",
//     date: "2022",
//     credentialId: "OOP-JAVA-2022-9012",
//     skills: ["Java", "OOP", "Design Patterns", "Testing", "Debugging"],
//     description:
//       "In-depth specialization on object-oriented programming principles and Java development.",
//     level: "Intermediate",
//     hours: "150+ hours",
//     courses: 4,
//     link: "https://drive.google.com/file/d/1UCWhNDc0QyQlWk_nkJYQ_2JXz7QwCU3k/view?usp=drivesdk",
//     featured: true,
//     icon: FaUniversity,
//     color: "from-orange-600 to-red-600",
//     bgColor: "bg-orange-50 dark:bg-orange-900/20",
//     borderColor: "border-orange-200 dark:border-orange-800",
//     iconBg: "bg-orange-100 dark:bg-orange-900/40",
//     gradient: "from-orange-500 to-red-500",
//   },
//   {
//     id: "cert-4",
//     type: "certification",
//     title: "Python for Everybody Specialization",
//     organization: "University of Michigan",
//     logo: SiPython,
//     issuer: "University of Michigan",
//     date: "2022",
//     credentialId: "PY4E-2022-3456",
//     skills: ["Python", "Web Scraping", "APIs", "Databases", "Data Analysis"],
//     description:
//       "Comprehensive Python programming specialization covering basics to advanced topics.",
//     level: "Intermediate",
//     hours: "160+ hours",
//     courses: 5,
//     link: "https://github.com/ahmedeid101/Python-for-Everybody-Specialization#readme",
//     featured: true,
//     icon: SiPython,
//     color: "from-yellow-600 to-amber-600",
//     bgColor: "bg-yellow-50 dark:bg-yellow-900/20",
//     borderColor: "border-yellow-200 dark:border-yellow-800",
//     iconBg: "bg-yellow-100 dark:bg-yellow-900/40",
//     gradient: "from-yellow-500 to-amber-500",
//   },
//   {
//     id: "cert-5",
//     type: "certification",
//     title: "Front End Web Development Professional",
//     organization: "Udacity",
//     logo: SiUdacity,
//     issuer: "Udacity",
//     date: "2023",
//     credentialId: "UDACITY-FEND-2023-7890",
//     skills: [
//       "HTML5",
//       "CSS3",
//       "JavaScript",
//       "React",
//       "Responsive Design",
//       "Web Performance",
//     ],
//     description:
//       "Professional nanodegree program focused on modern front-end development.",
//     level: "Professional",
//     hours: "200+ hours",
//     projects: 5,
//     link: "https://www.udacity.com/certificate/e/b7ea0d52-7ba4-11eb-92fc-c7fb52a7eaca",
//     featured: true,
//     icon: SiUdacity,
//     color: "from-cyan-600 to-blue-600",
//     bgColor: "bg-cyan-50 dark:bg-cyan-900/20",
//     borderColor: "border-cyan-200 dark:border-cyan-800",
//     iconBg: "bg-cyan-100 dark:bg-cyan-900/40",
//     gradient: "from-cyan-500 to-blue-500",
//   },
//   {
//     id: "cert-6",
//     type: "certification",
//     title: "Advanced Full-Stack Web Development",
//     organization: "Udacity",
//     logo: SiUdacity,
//     issuer: "Udacity",
//     date: "2023",
//     credentialId: "UDACITY-FULLSTACK-2023-1234",
//     skills: [
//       "React",
//       "Node.js",
//       "Express",
//       "MongoDB",
//       "GraphQL",
//       "AWS",
//       "Docker",
//     ],
//     description:
//       "Advanced nanodegree covering full-stack development with modern technologies.",
//     level: "Advanced",
//     hours: "250+ hours",
//     projects: 6,
//     link: "https://www.udacity.com/certificate/e/b7ea0d52-7ba4-11eb-92fc-c7fb52a7eaca",
//     featured: true,
//     icon: SiUdacity,
//     color: "from-indigo-600 to-purple-600",
//     bgColor: "bg-indigo-50 dark:bg-indigo-900/20",
//     borderColor: "border-indigo-200 dark:border-indigo-800",
//     iconBg: "bg-indigo-100 dark:bg-indigo-900/40",
//     gradient: "from-indigo-500 to-purple-500",
//   },
//   {
//     id: "cert-7",
//     type: "certification",
//     title: "Mean Stack Development",
//     organization: "Information Technology Institute (ITI)",
//     logo: SiNodedotjs,
//     issuer: "ITI",
//     date: "2023",
//     credentialId: "ITI-MEAN-2023-5678",
//     skills: [
//       "MongoDB",
//       "Express",
//       "Angular",
//       "Node.js",
//       "TypeScript",
//       "REST APIs",
//     ],
//     description:
//       "Intensive program on MEAN stack development with hands-on projects.",
//     level: "Professional",
//     hours: "180+ hours",
//     projects: 4,
//     link: "https://drive.google.com/file/d/1DzamOFI7spdnyetsO0xGv1isMRpPGZk4/view?usp=drivesdk",
//     featured: false,
//     icon: SiNodedotjs,
//     color: "from-emerald-600 to-green-600",
//     bgColor: "bg-emerald-50 dark:bg-emerald-900/20",
//     borderColor: "border-emerald-200 dark:border-emerald-800",
//     iconBg: "bg-emerald-100 dark:bg-emerald-900/40",
//     gradient: "from-emerald-500 to-green-500",
//   },
//   {
//     id: "cert-8",
//     type: "certification",
//     title: "Developing Web Application Using Python",
//     organization: "Information Technology Institute (ITI)",
//     logo: SiPython,
//     issuer: "ITI",
//     date: "2022",
//     credentialId: "ITI-PYTHON-2022-9012",
//     skills: ["Python", "Django", "Flask", "SQL", "REST APIs", "Testing"],
//     description:
//       "Comprehensive program on web development using Python frameworks.",
//     level: "Intermediate",
//     hours: "150+ hours",
//     projects: 3,
//     link: "https://drive.google.com/file/d/1UCWhNDc0QyQlWk_nkJYQ_2JXz7QwCU3k/view?usp=drivesdk",
//     featured: false,
//     icon: SiPython,
//     color: "from-teal-600 to-cyan-600",
//     bgColor: "bg-teal-50 dark:bg-teal-900/20",
//     borderColor: "border-teal-200 dark:border-teal-800",
//     iconBg: "bg-teal-100 dark:bg-teal-900/40",
//     gradient: "from-teal-500 to-cyan-500",
//   },
// ];
