// Education Data

import { FiBook } from "react-icons/fi";
import { FaUniversity } from "react-icons/fa";
import { GiGraduateCap } from "react-icons/gi";
import { SiPython, SiNodedotjs, SiUdacity } from "react-icons/si";

export const education = [
  {
    id: "edu-1",
    type: "education",
    institution: "Al-Azhar University",
    logo: GiGraduateCap,
    degree: "BSc in System and Computer Engineering",
    faculty: "Faculty of Engineering, System and Computer Department",
    location: "Cairo, Egypt",
    period: "2018 – 2023",
    status: "Completed",
    grade: "Very Good",
    activities: [
      "Member, Google Developer Students Club",
      "Participated in multiple hackathons",
      "Led university coding workshops",
    ],
    achievements: [
      "Graduation Project: Secured Examination Management System (Grade: Excellent)",
      "Best Project Award in Faculty Competition",
    ],
    icon: FiBook,
    color: "from-blue-600 to-indigo-600",
    bgColor: "bg-blue-50 dark:bg-blue-900/20",
    borderColor: "border-blue-200 dark:border-blue-800",
    iconBg: "bg-blue-100 dark:bg-blue-900/40",
    gradient: "from-blue-500 to-indigo-500",
  },
];

export const certifications = [
  {
    id: "cert-1",
    type: "certification",
    title: "CS50X",
    organization: "Harvard University",
    logo: FaUniversity,
    issuer: "Harvard University",
    date: "2023",
    credentialId: "CS50X-2023-1234",
    skills: ["C", "Python", "SQL", "JavaScript", "HTML/CSS"],
    description:
      "Introduction to Computer Science covering fundamental concepts, algorithms, and web development.",
    level: "Advanced",
    hours: "120+ hours",
    link: "https://certificates.cs50.io/9f14eae1-98ae-465a-b657-f5a7fcd385b5.png?size=letter",
    featured: true,
    icon: FaUniversity,
    color: "from-purple-600 to-pink-600",
    bgColor: "bg-purple-50 dark:bg-purple-900/20",
    borderColor: "border-purple-200 dark:border-purple-800",
    iconBg: "bg-purple-100 dark:bg-purple-900/40",
    gradient: "from-purple-500 to-pink-500",
  },
  {
    id: "cert-2",
    type: "certification",
    title: "Data Structures and Algorithms Specialization",
    organization: "University of California San Diego",
    logo: FaUniversity,
    issuer: "UC San Diego",
    date: "2023",
    credentialId: "DSA-UCSD-2023-5678",
    skills: [
      "Algorithms",
      "Data Structures",
      "Java",
      "Problem Solving",
      "Complexity Analysis",
    ],
    description:
      "Comprehensive specialization covering algorithm design, data structures, and computational complexity.",
    level: "Advanced",
    hours: "180+ hours",
    courses: 6,
    link: "https://www.coursera.org/account/accomplishments/specialization/JRZ9DOL1TSP5",
    featured: true,
    icon: FaUniversity,
    color: "from-green-600 to-teal-600",
    bgColor: "bg-green-50 dark:bg-green-900/20",
    borderColor: "border-green-200 dark:border-green-800",
    iconBg: "bg-green-100 dark:bg-green-900/40",
    gradient: "from-green-500 to-teal-500",
  },
  {
    id: "cert-3",
    type: "certification",
    title: "Object Oriented Programming in Java Specialization",
    organization: "Duke University & UC San Diego",
    logo: FaUniversity,
    issuer: "Duke University",
    date: "2022",
    credentialId: "OOP-JAVA-2022-9012",
    skills: ["Java", "OOP", "Design Patterns", "Testing", "Debugging"],
    description:
      "In-depth specialization on object-oriented programming principles and Java development.",
    level: "Intermediate",
    hours: "150+ hours",
    courses: 4,
    link: "https://drive.google.com/file/d/1UCWhNDc0QyQlWk_nkJYQ_2JXz7QwCU3k/view?usp=drivesdk",
    featured: true,
    icon: FaUniversity,
    color: "from-orange-600 to-red-600",
    bgColor: "bg-orange-50 dark:bg-orange-900/20",
    borderColor: "border-orange-200 dark:border-orange-800",
    iconBg: "bg-orange-100 dark:bg-orange-900/40",
    gradient: "from-orange-500 to-red-500",
  },
  {
    id: "cert-4",
    type: "certification",
    title: "Python for Everybody Specialization",
    organization: "University of Michigan",
    logo: SiPython,
    issuer: "University of Michigan",
    date: "2022",
    credentialId: "PY4E-2022-3456",
    skills: ["Python", "Web Scraping", "APIs", "Databases", "Data Analysis"],
    description:
      "Comprehensive Python programming specialization covering basics to advanced topics.",
    level: "Intermediate",
    hours: "160+ hours",
    courses: 5,
    link: "https://github.com/ahmedeid101/Python-for-Everybody-Specialization#readme",
    featured: true,
    icon: SiPython,
    color: "from-yellow-600 to-amber-600",
    bgColor: "bg-yellow-50 dark:bg-yellow-900/20",
    borderColor: "border-yellow-200 dark:border-yellow-800",
    iconBg: "bg-yellow-100 dark:bg-yellow-900/40",
    gradient: "from-yellow-500 to-amber-500",
  },
  {
    id: "cert-5",
    type: "certification",
    title: "Front End Web Development Professional",
    organization: "Udacity",
    logo: SiUdacity,
    issuer: "Udacity",
    date: "2023",
    credentialId: "UDACITY-FEND-2023-7890",
    skills: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "React",
      "Responsive Design",
      "Web Performance",
    ],
    description:
      "Professional nanodegree program focused on modern front-end development.",
    level: "Professional",
    hours: "200+ hours",
    projects: 5,
    link: "https://www.udacity.com/certificate/e/b7ea0d52-7ba4-11eb-92fc-c7fb52a7eaca",
    featured: true,
    icon: SiUdacity,
    color: "from-cyan-600 to-blue-600",
    bgColor: "bg-cyan-50 dark:bg-cyan-900/20",
    borderColor: "border-cyan-200 dark:border-cyan-800",
    iconBg: "bg-cyan-100 dark:bg-cyan-900/40",
    gradient: "from-cyan-500 to-blue-500",
  },
  {
    id: "cert-6",
    type: "certification",
    title: "Advanced Full-Stack Web Development",
    organization: "Udacity",
    logo: SiUdacity,
    issuer: "Udacity",
    date: "2023",
    credentialId: "UDACITY-FULLSTACK-2023-1234",
    skills: [
      "React",
      "Node.js",
      "Express",
      "MongoDB",
      "GraphQL",
      "AWS",
      "Docker",
    ],
    description:
      "Advanced nanodegree covering full-stack development with modern technologies.",
    level: "Advanced",
    hours: "250+ hours",
    projects: 6,
    link: "https://www.udacity.com/certificate/e/b7ea0d52-7ba4-11eb-92fc-c7fb52a7eaca",
    featured: true,
    icon: SiUdacity,
    color: "from-indigo-600 to-purple-600",
    bgColor: "bg-indigo-50 dark:bg-indigo-900/20",
    borderColor: "border-indigo-200 dark:border-indigo-800",
    iconBg: "bg-indigo-100 dark:bg-indigo-900/40",
    gradient: "from-indigo-500 to-purple-500",
  },
  {
    id: "cert-7",
    type: "certification",
    title: "Mean Stack Development",
    organization: "Information Technology Institute (ITI)",
    logo: SiNodedotjs,
    issuer: "ITI",
    date: "2023",
    credentialId: "ITI-MEAN-2023-5678",
    skills: [
      "MongoDB",
      "Express",
      "Angular",
      "Node.js",
      "TypeScript",
      "REST APIs",
    ],
    description:
      "Intensive program on MEAN stack development with hands-on projects.",
    level: "Professional",
    hours: "180+ hours",
    projects: 4,
    link: "https://drive.google.com/file/d/1DzamOFI7spdnyetsO0xGv1isMRpPGZk4/view?usp=drivesdk",
    featured: false,
    icon: SiNodedotjs,
    color: "from-emerald-600 to-green-600",
    bgColor: "bg-emerald-50 dark:bg-emerald-900/20",
    borderColor: "border-emerald-200 dark:border-emerald-800",
    iconBg: "bg-emerald-100 dark:bg-emerald-900/40",
    gradient: "from-emerald-500 to-green-500",
  },
  {
    id: "cert-8",
    type: "certification",
    title: "Developing Web Application Using Python",
    organization: "Information Technology Institute (ITI)",
    logo: SiPython,
    issuer: "ITI",
    date: "2022",
    credentialId: "ITI-PYTHON-2022-9012",
    skills: ["Python", "Django", "Flask", "SQL", "REST APIs", "Testing"],
    description:
      "Comprehensive program on web development using Python frameworks.",
    level: "Intermediate",
    hours: "150+ hours",
    projects: 3,
    link: "https://drive.google.com/file/d/1UCWhNDc0QyQlWk_nkJYQ_2JXz7QwCU3k/view?usp=drivesdk",
    featured: false,
    icon: SiPython,
    color: "from-teal-600 to-cyan-600",
    bgColor: "bg-teal-50 dark:bg-teal-900/20",
    borderColor: "border-teal-200 dark:border-teal-800",
    iconBg: "bg-teal-100 dark:bg-teal-900/40",
    gradient: "from-teal-500 to-cyan-500",
  },
];
